# Generated by Django 5.1.1 on 2024-10-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_registrotemperatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioArduino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('codigo_arduino', models.CharField(max_length=10, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
